### ISSUE TITLE
Parallel execution not does work with mock objects

### ISSUE THREAD

**Issue by Liam-Scott-Russell** [zacps/memento#44]
Trying to use a mock object to assert calls is not possible with the current implementation of parallelization. 
Been trying to verify that the caching function is entirely threadsafe and works, and this is the best way to test that.

From inspection, it seems like a new mock object is created, which does not reference the original.

Here is an example of code that doesn't work
```python
from unittest.mock import Mock

def test_mock_object_preserved():
    mock_func = Mock(return_value="output")

    manager = TaskManager()
    manager.add_task(delayed(mock_func)("input"))
    results = manager.run()

    assert results == ["output"] # works fine
    mock_func.assert_called_once_with("input") # breaks
```

**Comment by zacps** [comment]
Expected behaviour.
